Prep css flexbox
josephhparkk/prep-0922-code-solutions pull request #8
Opened 2022-09-26 04:03 UTC by josephhparkk

![Screen Shot 2022-09-25 at 9 02 33 PM](https://user-images.githubusercontent.com/113474457/192191464-6696cd0d-8db1-4a29-96a7-da68ea94de25.png)
![Screen Shot 2022-09-25 at 9 02 27 PM](https://user-images.githubusercontent.com/113474457/192191466-1419db46-9d26-4f4b-ba9f-db774d113278.png)
![Screen Shot 2022-09-25 at 9 02 22 PM](https://user-images.githubusercontent.com/113474457/192191468-dbcb3803-03ed-4cd2-86dc-139949156042.png)
![Screen Shot 2022-09-25 at 9 02 13 PM](https://user-images.githubusercontent.com/113474457/192191469-ce76cc1e-c931-448e-9367-12048fe8e6fa.png)

2022-09-26 16:47 UTC, thebearingedge requested changes

2022-09-26 16:47 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      flex-basis: calc(100%/3);
`flex-basis` only has any effect on "flex items", so you'll want to move it to a rule set for `.card-wrapper`

2022-09-26 19:48 UTC, josephhparkk commented
<img width="1680" alt="Screen Shot 2022-09-26 at 12 48 03 PM" src="https://user-images.githubusercontent.com/113474457/192366573-9a930c39-3c9a-4c02-9421-4f2f2f573a1a.png">
 made the changes!

2022-09-27 01:29 UTC, thebearingedge approved these changes

2022-09-29 06:26 UTC, merged